package org.cafiaso.server.network.packet.client.login;

import org.cafiaso.server.network.Serializer;
import org.cafiaso.server.network.packet.client.ClientPacket;
import org.cafiaso.server.network.packet.server.login.EncryptionRequestPacket;
import org.cafiaso.server.network.stream.input.InputStream;

import java.io.IOException;
import java.util.Arrays;

/**
 * Packet sent by the client in response to a {@link EncryptionRequestPacket}.
 *
 * @see <a href="https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Protocol#Encryption_Response">Encryption Response Packet</a>
 */
public class EncryptionResponsePacket implements ClientPacket {

    private byte[] sharedSecret;
    private byte[] verifyToken;

    @Override
    public void read(InputStream in) throws IOException {
        sharedSecret = in.read(Serializer.PREFIXED_BYTE_ARRAY);
        verifyToken = in.read(Serializer.PREFIXED_BYTE_ARRAY);
    }

    /**
     * Gets the shared secret generated by the client.
     *
     * @return the shared secret
     */
    public byte[] getSharedSecret() {
        return sharedSecret;
    }

    /**
     * Gets the verify token sent by the server.
     *
     * @return the verify token
     */
    public byte[] getVerifyToken() {
        return verifyToken;
    }

    @Override
    public String toString() {
        return "EncryptionResponsePacket{" +
                "sharedSecret=" + Arrays.toString(sharedSecret) +
                ", verifyToken=" + Arrays.toString(verifyToken) +
                '}';
    }
}
